package com.sngs.swayam.temp;

public class Constant {

    public static int WHO_Step = 10000;
    public static int WHO_Distance = 100;
    public static int WHO_Calory = 70;
    public static int TotalCalory = 0;
    public static int Glass_Of_Water = 0;
    public static int TotalGlass_Of_Water = 12;
    public static String[] Categories = new String[]{"B/fast", "Beverages", "Breads", "Eggs", "Fruits", "Juice", "Baked Goods",
            "Dairy", "Fast Foods", "Fats and Oils", "Fish", "Fruit", "Grain/Cereal", "Legumes/Nuts", "Meat/Poultry", "Miscellaneous", "Mixed Dishes", "Snacks", "Soups", "Sweets", "Vegetables"};
    public static String[] Item_fast = new String[]{"Puri",
            "Bhaji",
            "Gulugula",
            "Idly",
            "Sambhar",
            "Samosa",
            "Vada",
            "Boiled Vegetable",
            "Aloo bonda",
            "Utthapam",
            "Pan Cake(chakuli)",
            "Dosa Plain",
            "Masala Dosa",
            "Paratha  ",
            "Aloo Paratha",
            "Gobi Paratha",
            "Chapati",
            "Bhel Puri",
            "Pani Puri(Gup-Chup)",
            "Upma",
            "Puha",
            "Dahi vada",
            "Vegetable Roll",
            "Channa Chaat",
            "Choley",
            "Bhutara",
            "Dahi vada Aloo dum ",
            "Vegetable Pakoda",
            "Veg Chowmin",
            "Kaakara",
            "Aadisha",
            "Porridge with milk"
    };
    public static String[] Item_fast_QTY = new String[]{"1",
            "1 cup",
            "1",
            "1",
            "1 cup",
            "1",
            "1",
            "1 bowl",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1 plate",
            "1 plate",
            "1 portion",
            "1 portion",
            "1 bowl",
            "1",
            "1 portion",
            "1 portion",
            "1",
            "1 portion",
            "1 portion",
            "1 portion",
            "1",
            "1",
            "1"};
    public static String[] Item_fast_Calories = new String[]{"75",
            "150",
            "80",
            "100",
            "150",
            "110",
            "100",
            "110",
            "110",
            "100",
            "100",
            "120",
            "250",
            "150",
            "290",
            "270",
            "60",
            "150",
            "150",
            "180",
            "110",
            "350",
            "244",
            "180",
            "160",
            "90",
            "250",
            "280",
            "160",
            "180",
            "200",
            "210"};
    public static String[] Item_Beverages = new String[]{"Coffee Black",
            "Coffee with milk",
            "Tea with milk",
            "Green tea",
            "Milk Shake",
            "Coconut water",
            "Lassi",
            "Mango Lassi",
            "Coconut Milk",
            "Buttermilk", "Beer, light (4% alcohol by volume)",
            "Beer, regular (5% alcohol by volume)",
            "Club soda",
            "Cocktail,  daiquiri",
            "Cocktail,  margarita",
            "Coffee, brewed",
            "Coffee, latte",
            "Cola",
            "Ginger ale",
            "Iced coffee, Frappuccino (StarbucksTM)",
            "Lemonade, pink or white, frozen, diluted",
            "Mixed vegetable and fruit juice drink, ready-to-drink",
            "Spirits (gin, rum, vodka, whisky)",
            "Sports drink, fruit flavour, ready-to-drink (GatoradeTM,",
            "Tea, brewed",
            "Water, mineral (PerrierTM)",
            "Water, municipal",
            "Wine, table, red",
            "Wine, table, white"};
    public static String[] Item_Beverages_QTY = new String[]{"1 cup",
            "1 cup",
            "1 cup",
            "1 cup",
            "1 gls",
            "1 gls",
            "1 gls",
            "1 gls",
            "1 gls",
            "1 gls",
            "1 bottle",
            "1 bottle",
            "250 ML",
            "125 ML",
            "125 ML",
            "250 ML",
            "250 ML",
            "250 ML",
            "250 ML",
            "250 ML",
            "250 ML",
            "250 ML",
            "50 ML",
            "250 ML",
            "250 ML",
            "250 ML",
            "250 ML",
            "125 ML",
            "125 ML"};
    public static String[] Item_Beverages_Calories = new String[]{"15",
            "40",
            "50",
            "4",
            "200",
            "46",
            "100",
            "158",
            "559",
            "104",
            "99",
            "140",
            "0",
            "237",
            "246",
            "3",
            "101",
            "110",
            "88",
            "127",
            "105",
            "113",
            "109",
            "67",
            "3",
            "0",
            "0",
            "90",
            "85"};
    public static String[] Item_Breads = new String[]{"Bread slice with Butter",
            "Naan",
            "Roti/chapati/Phulka",
            "Kulcha Naan",
            "Missi Roti",
            "Tandoori Roti",
            "Tandoori Roti with Butter",
            "Banana bread, homemade (11cm X 6cm X 1cm)",
            "Roomali Roti",
            "Bajra ki Roti"};

    public static String[] Item_Breads_QTY = new String[]{"1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1 slice",
            "1",
            "1"};
    public static String[] Item_Breads_Calories = new String[]{"90",
            "80",
            "60",
            "130",
            "125",
            "102",
            "147",
            "196",
            "200",
            "108"};
    public static String[] Item_Eggs = new String[]{
            "Egg, hard-boiled",
            "Egg, fried",
            "Egg, poached",
            "Egg white, cooked",
            "Omelette Masala",
            "Egg yolk, cooked"
    };
    public static String[] Item_Eggs_QTY = new String[]{"1",
            "2",
            "1",
            "1",
            "2",
            "1"};
    public static String[] Item_Eggs_Calories = new String[]{"78",
            "173",
            "74",
            "16",
            "120",
            "59"};
    public static String[] Item_Fruits = new String[]{"Apple",
            "Orange",
            "Banana",
            "Grapes",
            "Custard Apple",
            "Mango ",
            "Pomenegrate",
            "Pineapple",
            "Jackfruit",
            "Raisins",
            "Lychees",
            "Pear",
            "Papaya",
            "Fruit Salad",
            "Figs",
            "Watermelon",
            "Kiwi",
            "Sweet Lime",
            "Lemon",
            "Dates",
            "Gouava"};
    public static String[] Item_Fruits_QTY = new String[]{"1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "150 gm",
            "145 gm",
            "1",
            "1",
            "500 gm",
            "1 bowl",
            "1",
            "250 gm",
            "1",
            "1",
            "1",
            "1",
            "1"};
    public static String[] Item_Fruits_Calories = new String[]{"95",
            "62",
            "111",
            "104",
            "136",
            "202",
            "234",
            "190",
            "143",
            "434",
            "7",
            "101",
            "215",
            "125",
            "20",
            "80",
            "112",
            "20",
            "17",
            "20",
            "40"};
    public static String[] Item_Juice = new String[]{"Aloe Vera",
            "Apple juice",
            "Banana Juice",
            "Carrot Juice",
            "Cucumber Juice",
            "Grape Juice",
            "Orange Juice",
            "Papaya Juice",
            "Pear Juice",
            "Pinaple Juice",
            "Pomegranate Juice",
            "Sugarcane Juice"};
    public static String[] Item_Juice_QTY = new String[]{"240 ML",
            "240 ML",
            "240 ML",
            "240 ML",
            "240 ML",
            "240 ML",
            "240 ML",
            "240 ML",
            "240 ML",
            "240 ML",
            "240 ML",
            "240 ML"};
    public static String[] Item_Juice_Calories = new String[]{"139",
            "110",
            "120",
            "96",
            "26",
            "144",
            "110",
            "139",
            "144",
            "127",
            "158",
            "150"};
    public static String[] Item_BakedGoods = new String[]{"Animal crackers (arrowroot, social tea)",
            "Apple crisp, homemade",
            "Banana bread, homemade (11cm X 6cm X 1cm)",
            "Butter tart",
            "Croissant, butter",
            "Danish pastry, fruit (11cm diam)",
            "Doughnut, cake-type, plain (8cm diam)",
            "Ginger snaps",
            "Graham crackers, plain or honey",
            "Granola bar, soft, nuts and raisins",
            "Muffin, bran, homemade",
            "Sugar cookies, commercial",
            "Toaster pastries ( Pop-TartsTM), brown sugar & cinnamon",
            "Toaster pastries (Pop-TartsTM), fruit, frosted"};
    public static String[] Item_BakedGoods_QTY = new String[]{"2",
            "125 ML",
            "1 slice",
            "1",
            "1",
            "1",
            "1",
            "2",
            "2",
            "1",
            "1",
            "2",
            "1",
            "1"};
    public static String[] Item_BakedGoods_Calories = new String[]{"45",
            "206",
            "196",
            "248",
            "231",
            "263",
            "198",
            "58",
            "59",
            "127",
            "199",
            "143",
            "206",
            "215"};
    public static String[] Item_Dairy = new String[]{"Buttermilk",
            "Cheese, Cheddar",
            "Coffee whitener, powdered, light",
            "Eggnog",
            "Hot chocolate, powder , water",
            "Milk,  chocolate, 1% M.F.",
            "Milk,  condensed, sweetened, canned (Eagle BrandTM)",
            "Milk, evaporated, partly skimmed, canned, diluted, 2% M.F.",
            "Milk, partly skimmed, 1% M.F.",
            "Milk, partly skimmed, 2% M.F.",
            "Milk, skim",
            "Milk, whole, 3.3% M.F.",
            "Soy beverage, original and vanilla, enriched",
            "Yogourt, plain, 1-2% M.F.",
            "Yogourt, plain, fat-free",
            "Yogourt, vanilla or fruit, 1-2% M.F.",
            "Yogourt, vanilla or fruit, fat-free"};
    public static String[] Item_Dairy_QTY = new String[]{"250 ML",
            "50g",
            "5 ML",
            "250 ML",
            "250 ML",
            "250 ML",
            "15 ML",
            "250 ML",
            "250 ML",
            "250 ML",
            "250 ML",
            "250 ML",
            "250 ML",
            "175 ML",
            "175 ML",
            "175 ML",
            "175 ML"};
    public static String[] Item_Dairy_Calories = new String[]{"104",
            "202",
            "9",
            "362",
            "160",
            "166",
            "62",
            "122",
            "108",
            "129",
            "88",
            "155",
            "110",
            "114",
            "79",
            "183",
            "116"};

    public static String[] Item_Fast_Foods = new String[]{"Breakfast biscuit with egg, cheese and bacon",
            "Breakfast English muffin with egg, cheese and bacon",
            "Cheeseburger, double patty , condiments , vegetables",
            "Cheeseburger, single patty, plain",
            "Chicken chow mein",
            "Chicken fried rice",
            "Chicken, breaded and fried, boneless (nuggets)",
            "Chili con carne",
            "Corndog (PogoTM)",
            "Donair /  Gyro",
            "Egg roll",
            "Fish sandwich with breaded fish",
            "French fries",
            "Garlic bread",
            "Hamburger, double patty , condiments",
            "Hamburger, single patty, plain",
            "Hot-dog, plain",
            "Milk shake, chocolate",
            "Milk shake, vanilla",
            "Onion rings, breaded and fried",
            "Pizza with cheese (medium - 12 inches)",
            "Pizza with cheese and pepperoni (medium - 12 inches)",
            "Submarine sandwich (6 inches), with cold cuts",
            "Wrap sandwich, chicken ranch"};
    public static String[] Item_Fast_Foods_QTY = new String[]{"1",
            "1",
            "1",
            "1",
            "250 ML",
            "250 ML",
            "6",
            "250 ML",
            "1",
            "1",
            "1",
            "1",
            "20-25 fries",
            "2 slices",
            "1",
            "1",
            "1",
            "250 ML",
            "250 ML",
            "8-Sep",
            "1-Jun",
            "1-Jun",
            "1",
            "1"};
    public static String[] Item_Fast_Foods_Calories = new String[]{"477",
            "289",
            "650",
            "319",
            "200",
            "343",
            "285",
            "270",
            "197",
            "310",
            "113",
            "523",
            "236",
            "192",
            "576",
            "275",
            "242",
            "223",
            "195",
            "276",
            "210",
            "219",
            "456",
            "532"};

    public static String[] Item_Fats_Oils = new String[]{"Butter",
            "Lard",
            "Margarine, tub, composite",
            "Oil, Canola",
            "Oil, Corn",
            "Oil, Flaxseed",
            "Oil, Grapeseed",
            "Oil, Olive",
            "Oil, Peanut",
            "Oil, Sesame",
            "Oil, Soybean",
            "Oil, Sunflower",
            "Salad dressing, Blue cheese",
            "Salad dressing, Creamy Caesar",
            "Salad dressing, French",
            "Salad dressing, Italian",
            "Salad dressing, Italian, low Calorie",
            "Salad dressing, Mayonnaise",
            "Salad dressing, Oil and vinegar",
            "Salad dressing, Ranch",
            "Shortening"};
    public static String[] Item_Fats_Oils_QTY = new String[]{"5 ML",
            "15 ML",
            "5 ML",
            "15 ML",
            "15 ML",
            "15 ML",
            "15 ML",
            "15 ML",
            "15 ML",
            "15 ML",
            "15 ML",
            "15 ML",
            "15 ML",
            "15 ML",
            "15 ML",
            "15 ML",
            "15 ML",
            "15 ML",
            "15 ML",
            "15 ML",
            "15 ML"};
    public static String[] Item_Fats_Oils_Calories = new String[]{"34",
            "117",
            "34",
            "125",
            "122",
            "122",
            "122",
            "121",
            "121",
            "122",
            "122",
            "122",
            "78",
            "79",
            "72",
            "43",
            "11",
            "100",
            "73",
            "71",
            "115"};

    public static String[] Item_Fish = new String[]{"Calamari, breaded and fried",
            "Caviar, black or red",
            "Clams, mixed species, boiled or steamed",
            "Crab cake",
            "Crab, imitation, made from surimi",
            "Crab, snow, boiled or steamed",
            "Fish cake",
            "Fish fillet, battered and fried",
            "Fish sticks, frozen, heated (10cm x 2.5cm x 1.3cm)",
            "Haddock, baked or broiled",
            "Halibut, Atlantic and Pacific, baked or broiled",
            "Lobster, boiled or steamed",
            "Mussels, boiled or steamed",
            "Oysters, boiled or steamed",
            "Salmon, Atlantic, farmed, baked or broiled",
            "Salmon, smoked",
            "Scallops, cooked, steamed",
            "Shrimp, boiled or steamed",
            "Shrimp, breaded and fried",
            "Sole (flatfish), baked or broiled",
            "Tuna, light, canned in water, drained, salted",
            "Tuna, light, canned with oil, drained, salted"};

    public static String[] Item_Fish_QTY = new String[]{"125 ML",
            "15 ML",
            "5 large",
            "1",
            "125 ML",
            "125 ML",
            "1",
            "1",
            "3 sticks",
            "75 g",
            "75 g",
            "125 ML",
            "15 small",
            "6 medium",
            "75 g",
            "2 pieces",
            "6 medium",
            "6 medium",
            "6 medium",
            "75 g",
            "75 g",
            "75 g"};
    public static String[] Item_Fish_Calories = new String[]{"156",
            "41",
            "89",
            "93",
            "68",
            "72",
            "240",
            "265",
            "227",
            "84",
            "105",
            "75",
            "129",
            "58",
            "155",
            "47",
            "87",
            "30",
            "160",
            "88",
            "87",
            "149"};

    public static String[] Item_Fruit = new String[]{"Apple juice, ready-to-drink, vitamin C added",
            "Apple with skin (7cm.diam)",
            "Applesauce, unsweetened",
            "Apricots, dried",
            "Apricots, raw",
            "Avocado",
            "Banana",
            "Blackberries",
            "Blueberries, frozen, unsweetened",
            "Blueberries, raw",
            "Cherries, sweet",
            "Clementine",
            "Cranberries, dried, sweetened",
            "Cranberry juice cocktail, ready-to-drink, vitamin C added",
            "Dates, dried",
            "Figs, dried",
            "Figs, raw",
            "Fruit cocktail, canned, juice pack",
            "Grape juice, ready-to-drink, vitamin C added",
            "Grapefruit juice, ready-to-drink unsweetened or freshly",
            "Grapefruit, white",
            "Grapes",
            "Kiwifruit",
            "Lemon juice, canned or bottled",
            "Lime juice, canned or bottled",
            "Mango",
            "Melon, cantaloupe, cubes",
            "Nectarine",
            "Orange",
            "Orange juice, ready-to-drink",
            "Papaya, cubes",
            "Peach",
            "Peach, canned halves or slices, juice pack",
            "Pear with skin",
            "Pear, canned halves, juice pack",
            "Pear, canned halves, light syrup pack",
            "Pineapple, cubes",
            "Plum",
            "Prune juice, ready-to-drink",
            "Prunes, dried",
            "Raisins",
            "Raspberries",
            "Strawberries",
            "Tangerine (mandarin)"};
    public static String[] Item_Fruit_QTY = new String[]{"125 ML",
            "1",
            "125 ML",
            "3",
            "3",
            "1-Feb",
            "1",
            "125 ML",
            "125 ML",
            "125 ML",
            "10",
            "1",
            "60 ML",
            "125 ML",
            "3",
            "2",
            "1",
            "125 ML",
            "125 ML",
            "125 ML",
            "1-Feb",
            "20",
            "1",
            "15 ML",
            "15 ML",
            "1-Feb",
            "125 ML",
            "1",
            "1",
            "125 ML",
            "125 ML",
            "1",
            "125 ML",
            "1",
            "125 ML",
            "125 ML",
            "125 ML",
            "1",
            "125 ML",
            "3",
            "60 ML",
            "125 ML",
            "7",
            "1"};
    public static String[] Item_Fruit_Calories = new String[]{"59",
            "72",
            "55",
            "67",
            "50",
            "161",
            "105",
            "33",
            "42",
            "44",
            "43",
            "35",
            "95",
            "76",
            "70",
            "42",
            "37",
            "58",
            "81",
            "50",
            "39",
            "69",
            "46",
            "3",
            "3",
            "67",
            "29",
            "60",
            "62",
            "58",
            "29",
            "38",
            "58",
            "96",
            "66",
            "76",
            "42",
            "30",
            "96",
            "60",
            "110",
            "34",
            "27",
            "45"};
    public static String[] Item_Grain_Cereal = new String[]{"All Bran, Kellogg’sTM",
            "Bagel, plain (10cm diam)",
            "Bread stick, plain (19cm X 2cm)",
            "Bread, mixed-grain",
            "Bread, white, commercial",
            "Bread, whole wheat, commercial",
            "Cheerios, regular General MillsTM",
            "Cheese crackers, small",
            "Corn Flakes, Kellogg’sTM",
            "Macaroni, cooked",
            "Melba toast, plain",
            "Milk crackers",
            "Muesli, President’s ChoiceTM",
            "Oatmeal, instant, regular",
            "Rice Krispies, Kellogg’sTM",
            "Rice, brown, long-grain, cooked",
            "Rice, white, long-grain, cooked",
            "Roll, dinner, white",
            "Roll, dinner, whole wheat",
            "Rusk toast",
            "Saltine (oyster, soda, soup)",
            "Saltine (oyster, soda, soup), unsalted top",
            "Soba noodles, cooked",
            "Spaghetti, cooked",
            "Spaghetti, whole wheat, cooked",
            "Special K, Kellogg’sTM",
            "Taco shell, baked (13cm diam)",
            "Tortilla, corn (15cm diam)",
            "Tortilla, wheat (20cm diam)",
            "Whole wheat crackers"};
    public static String[] Item_Grain_QTY = new String[]{"125 ML",
            "1",
            "1",
            "1 slice",
            "1 slice",
            "1 slice",
            "250 ML",
            "15",
            "250 ML",
            "250 ML",
            "2",
            "2",
            "75 ML",
            "1 packet",
            "250 ML",
            "125 ML",
            "125 ML",
            "1",
            "1",
            "1",
            "4",
            "4",
            "250 ML",
            "250 ML",
            "250 ML",
            "250 ML",
            "1 shell",
            "1",
            "1",
            "4"};
    public static String[] Item_Grain_Calories = new String[]{"92",
            "195",
            "41",
            "88",
            "93",
            "86",
            "95",
            "75",
            "103",
            "209",
            "39",
            "109",
            "144",
            "112",
            "110",
            "115",
            "109",
            "85",
            "75",
            "41",
            "51",
            "52",
            "119",
            "209",
            "183",
            "94",
            "61",
            "41",
            "159",
            "71"};

    public static String[] Item_Legumes_Nuts = new String[]{"Almond butter",
            "Almonds, dried",
            "Beans,  kidney, dark red, canned, not drained",
            "Beans, baked, plain or vegetarian, canned",
            "Beans, black, canned, not drained",
            "Brazil nuts, dried",
            "Cashews, roasted, salted",
            "Chickpeas ( garbanzo beans), canned, not drained",
            "Lentils, boiled, salted",
            "Mixed nuts, roasted, salted",
            "Peanut butter, smooth type, fat, sugar and salt added",
            "Peanut butter, smooth type, light",
            "Peanuts, all types, shelled, roasted",
            "Pecans, dried",
            "Soy patty",
            "Sunflower seed kernels, roasted, salted",
            "Tofu, regular, firm and extra firm",
            "Walnuts, dried"};
    public static String[] Item_Legume_QTY = new String[]{"30 ML",
            "60 ML",
            "175 ML",
            "175 ML",
            "175 ML",
            "60 ML",
            "60 ML",
            "175 ML",
            "175 ML",
            "60 ML",
            "30 ML",
            "30 ML",
            "60 ML",
            "60 ML",
            "1",
            "60 ML",
            "150 g",
            "60 ML"};
    public static String[] Item_Legume_Calories = new String[]{"205",
            "208",
            "161",
            "177",
            "162",
            "233",
            "199",
            "211",
            "170",
            "206",
            "191",
            "190",
            "217",
            "173",
            "136",
            "189",
            "189",
            "166"};

    public static String[] Item_Meat_Poultry = new String[]{"Back bacon, pork, grilled",
            "Bacon, pork, broiled, pan-fried or roasted",
            "Beef, Ground, extra lean, crumbled, pan-fried",
            "Beef, Ground, lean, crumbled, pan-fried",
            "Beef, Ground, medium, crumbled, pan-fried",
            "Beef, Ground, regular, crumbled, pan-fried",
            "Beef, Rib steak, lean , fat, broiled",
            "Beef, Rump roast, lean , fat, broiled",
            "Beef, Sirloin tip roast, lean , fat, roasted",
            "Beef, Stewing beef, lean, simmered",
            "Beef, Strip loin (New York) steak, lean , fat, broiled",
            "Beef, T-Bone (Porterhouse) steak, lean , fat, broiled",
            "Beef, Tenderloin, steak, lean , fat, broiled",
            "Bologna (baloney), beef and pork",
            "Chicken, broiler, breast, meat and skin, roasted",
            "Chicken, broiler, breast, meat, roasted",
            "Chicken, broiler, drumstick, meat and skin, roasted",
            "Chicken, broiler, drumstick, meat, roasted",
            "Chicken, broiler, wing, meat and skin, roasted",
            "Chicken, canned, flaked",
            "Chicken, ground, lean, cooked",
            "Corned beef,  brisket, cooked",
            "Cottage roll, pork, lean and fat, roasted",
            "Deli meat, beef, thin sliced",
            "Deli meat, chicken breast roll",
            "Deli meat, ham, regular (11% fat)",
            "Deli meat, mock chicken, loaved",
            "Deli meat, turkey breast",
            "Ham, extra lean, canned",
            "Ham, lean, canned",
            "Ham, lean, roasted",
            "Kidney, beef, simmered",
            "Kielbasa (Kolbassa), pork and beef",
            "Lamb, American, fresh, ground, cooked",
            "Lamb, American, fresh, loin, lean , fat, cooked",
            "Lamb, New Zealand, frozen, loin, lean , fat, broiled",
            "Lamb, New Zealand, frozen, rib, lean , fat, roasted",
            "Liver, beef, pan-fried",
            "Pastrami, beef",
            "Pate, liver, canned",
            "Pepperoni, pork, beef",
            "Pork, Centre cut, loin, chop, lean , fat, broiled",
            "Pork, Centre cut, loin, chop, lean , fat, pan-fried",
            "Pork, Ground, medium, pan-fried",
            "Pork, Loin, rib end, lean , fat, broiled",
            "Pork, Shoulder, whole, lean , fat, roasted",
            "Pork, Spareribs, lean , fat, braised",
            "Pork, Tenderloin, lean, roasted",
            "Salami, beef and pork",
            "Sausage, breakfast, pork and beef, cooked",
            "Wiener (frankfurter), beef"};
    public static String[] Item_Meat_QTY = new String[]{"2 slices",
            "3 slices",
            "75 g",
            "75 g",
            "75 g",
            "75 g",
            "75 g",
            "75 g",
            "75 g",
            "75 g",
            "75 g",
            "75 g",
            "75 g",
            "2 slices",
            "75 g",
            "75 g",
            "75 g",
            "75 g",
            "75 g",
            "60 ML",
            "75 g",
            "2 slices",
            "2 slices",
            "4 slices",
            "2 slices",
            "2 slices",
            "2 slices",
            "2 slices",
            "2 slices",
            "2 slices",
            "75 g",
            "75 g",
            "1 piece",
            "75 g",
            "75 g",
            "75 g",
            "75 g",
            "75 g",
            "2 slices",
            "30 ML",
            "10 slices",
            "75 g",
            "75 g",
            "75 g",
            "75 g",
            "75 g",
            "75 g",
            "75 g",
            "2 slices",
            "1",
            "1"};
    public static String[] Item_Meat_Calories = new String[]{"87",
            "130",
            "167",
            "194",
            "214",
            "243",
            "232",
            "164",
            "156",
            "183",
            "191",
            "216",
            "170",
            "153",
            "142",
            "119",
            "161",
            "127",
            "218",
            "89",
            "153",
            "101",
            "69",
            "83",
            "75",
            "91",
            "147",
            "63",
            "62",
            "81",
            "118",
            "119",
            "124",
            "212",
            "232",
            "222",
            "238",
            "131",
            "74",
            "84",
            "252",
            "180",
            "208",
            "224",
            "197",
            "219",
            "251",
            "108",
            "118",
            "51",
            "104"};

    public static String[] Item_Miscellaneous = new String[]{"Bacon bits, simulated meat",
            "Gravy, beef, canned",
            "Gravy, chicken, canned",
            "Ketchup",
            "Mustard",
            "Olives, pickled, canned or bottled",
            "Olives, ripe, canned, jumbo",
            "Onion dip",
            "Pickle  relish, sweet",
            "Pickles, cucumber, sweet, slices",
            "Salsa",
            "Sauce,  soy",
            "Sauce,  steak (HPTM, A1TM)",
            "Sauce,  sweet and sour",
            "Sauce, barbecue",
            "Sauce, teriyaki",
            "Spinach dip"};
    public static String[] Item_Miscellaneous_QTY = new String[]{"15 ML",
            "60 ML",
            "60 ML",
            "15 ML",
            "15 ML",
            "4",
            "2",
            "30 ML",
            "15 ML",
            "4",
            "15 ML",
            "15 ML",
            "15 ML",
            "15 ML",
            "15 ML",
            "15 ML",
            "30 ML"};
    public static String[] Item_Miscellaneous_Calories = new String[]{"34",
            "31",
            "48",
            "15",
            "11",
            "23",
            "13",
            "50",
            "20",
            "33",
            "5",
            "7",
            "9",
            "20",
            "12",
            "15",
            "74"};

    public static String[] Item_MixedDishes = new String[]{"Burrito with beans and cheese",
            "Caesar Salad",
            "Caesar salad with chicken",
            "Chicken pot pie, commercial, individual",
            "Club sandwich",
            "Garden Salad",
            "Greek Salad",
            "Macaroni and cheese (Kraft DinnerTM)",
            "Poutine",
            "Stir fry with beef",
            "Sushi with fish",
            "Sushi with vegetables, no fish",
            "Taco with beef, cheese, salsa , vegetables"};
    public static String[] Item_MixedDishes_QTY = new String[]{"1",
            "250 ML",
            "500 ML",
            "1 serving",
            "1",
            "250 ML",
            "250 ML",
            "250 ML",
            "250 ML",
            "250 ML",
            "4",
            "4",
            "1"};
    public static String[] Item_MixedDishes_Calories = new String[]{"189",
            "179",
            "491",
            "494",
            "558",
            "47",
            "139",
            "395",
            "380",
            "290",
            "164",
            "122",
            "168"};

    public static String[] Item_Snacks = new String[]{"Beef jerky (22cm long)",
            "Corn-based puffs or twists, cheese (CheesiesTM)",
            "Popcorn, Air-popped",
            "Popcorn, Microwave, low fat and reduced salt",
            "Potato chips, plain",
            "Pretzels, hard, plain, salted",
            "Rice cakes, plain",
            "Tortilla chips, nacho flavoured (DoritosTM)",
            "Trail mix, regular"};
    public static String[] Item_Snacks_QTY = new String[]{"1 stick",
            "250 ML",
            "250 ML",
            "250 ML",
            "1 small bag",
            "10 sticks",
            "1",
            "1 small bag",
            "60 ML"};
    public static String[] Item_Snacks_Calories = new String[]{"81",
            "205",
            "32",
            "34",
            "230",
            "19",
            "35",
            "249",
            "176"};

    public static String[] Item_Soups = new String[]{"Soup, Chicken noodle",
            "Soup, Cream of mushroom",
            "Soup, Tomato",
            "Soup, Tomato, reduced salt",
            "Soup, Vegetables with beef",
            "Soup, Vegetarian vegetable"};
    public static String[] Item_Soups_QTY = new String[]{"250 ML",
            "250 ML",
            "250 ML",
            "250 ML",
            "250 ML",
            "250 ML"};
    public static String[] Item_Soups_Calories = new String[]{"79",
            "137",
            "90",
            "90",
            "83",
            "76"};

    public static String[] Item_Sweets = new String[]{"Brown sugar",
            "Frozen yogourt, chocolate",
            "Honey",
            "Ice cream cone, vanilla, soft serve",
            "Ice cream, vanilla, low fat",
            "Jams and preserves",
            "Maple syrup",
            "Milk  chocolate, bars or chips",
            "Popsicles",
            "Sherbet, orange",
            "Spread, chocolate hazelnut ( NutellaTM)",
            "Sugar substitute, aspartame ( EqualTM)",
            "White sugar (granulated)"};
    public static String[] Item_Sweets_QTY = new String[]{"5 ML",
            "125 ML",
            "5 ML",
            "1",
            "125 ML",
            "15 ML",
            "15 ML",
            "1 bar",
            "1",
            "125 ML",
            "30 ML",
            "1 packet",
            "5 ML"};
    public static String[] Item_Sweets_Calories = new String[]{"18",
            "116",
            "22",
            "266",
            "117",
            "56",
            "55",
            "268",
            "54",
            "113",
            "203",
            "4",
            "16"};

    public static String[] Item_Vegetables = new String[]{"Asparagus, fresh or frozen, boiled, drained",
            "Bean sprouts, stir-fried",
            "Beans, snap (green, yellow, Italian), canned, drained",
            "Beans, snap (green, yellow, Italian), fresh or frozen,",
            "Bok Choy,  Pak-Choi, shredded, boiled, drained",
            "Broccoli, chopped, boiled, drained",
            "Brussels sprouts, fresh or frozen, boiled, drained",
            "Cabbage, green, shredded, raw",
            "Carrot juice",
            "Carrots, raw",
            "Cauliflower, pieces, raw",
            "Celery, raw",
            "Corn, sweet, canned, niblets",
            "Cucumber, peeled, raw",
            "Edamame",
            "Leeks, chopped, boiled, drained",
            "Lettuce, iceberg, shredded",
            "Lettuce, romaine, shredded",
            "Mushrooms, pieces, canned, drained",
            "Mushrooms, raw",
            "Onions, green (scallion), raw",
            "Onions, yellow, chopped, raw",
            "Parsnip, sliced, boiled, drained",
            "Peas,  snowpeas, boiled, drained",
            "Peas, green, canned, drained",
            "Pepper, sweet, green, raw",
            "Pepper, sweet, red, raw",
            "Potato, baked, flesh and skin",
            "Potato, boiled without skin",
            "Potatoes, French fried, frozen, home-prepared in oven",
            "Rutabaga (yellow turnip), diced, boiled, drained",
            "Sauerkraut, canned, not drained",
            "Spinach, chopped, raw",
            "Squash, acorn, cubed, baked",
            "Sweet potato, boiled without skin",
            "Swiss chard, chopped, boiled, drained",
            "Tomato juice",
            "Tomato sauce, canned",
            "Tomatoes, canned, stewed",
            "Tomatoes, raw",
            "Vegetable juice cocktail",
            "Zucchini, raw, slices"};
    public static String[] Item_Vegetables_QTY = new String[]{"6 spears",
            "125 ML",
            "125 ML",
            "125 ML",
            "125 ML",
            "125 ML",
            "4 sprouts",
            "125 ML",
            "125 ML",
            "1 medium",
            "125 ML",
            "1 stalk",
            "125 ML",
            "4 slices",
            "125 ML",
            "125 ML",
            "250 ML",
            "250 ML",
            "125 ML",
            "3 medium",
            "1 medium",
            "60 ML",
            "125 ML",
            "125 ML",
            "125 ML",
            "1-Feb",
            "1-Feb",
            "1",
            "1",
            "20 strips",
            "125 ML",
            "125 ML",
            "250 ML",
            "125 ML",
            "1-Feb",
            "125 ML",
            "125 ML",
            "125 ML",
            "125 ML",
            "1",
            "125 ML",
            "4"};
    public static String[] Item_Vegetables_Calories = new String[]{"18",
            "33",
            "14",
            "22",
            "11",
            "29",
            "33",
            "9",
            "50",
            "25",
            "13",
            "6",
            "88",
            "3",
            "100",
            "17",
            "8",
            "10",
            "21",
            "12",
            "5",
            "17",
            "59",
            "36",
            "62",
            "16",
            "15",
            "161",
            "116",
            "96",
            "35",
            "14",
            "7",
            "61",
            "57",
            "18",
            "22",
            "41",
            "35",
            "22",
            "24",
            "6"};

}
